package su.logix.studperformance.main.connection;

import org.jetbrains.annotations.Contract;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class DBConnection {
    private static DBConnection ourInstance = new DBConnection();
    private Connection connection;
    private String connectionString;
    private String user;
    private String password;

    private DBConnection() {
    }

    @Contract(pure = true)
    public static DBConnection getInstance() {
        return ourInstance;
    }

    public void setParams(String connectionString, String user, String password) {
        this.connectionString = connectionString;
        this.user = user;
        this.password = password;
    }

    public void setParams(String connectionString) {
        setParams(connectionString, "", "");
    }

    public void connect() throws SQLException {
        if (connection == null || !isConnected()) {
            connection = DriverManager.getConnection(connectionString, user, password);
        }
    }

    public void disconnect() throws SQLException {
        if (isConnected()) {
            connection.close();
        }
    }

    public Statement getStatement() throws SQLException {
        return connection.createStatement();
    }

    public PreparedStatement getPreparedStatement(String query, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(query, autoGeneratedKeys);
    }

    public PreparedStatement getPreparedStatement(String query) throws SQLException {
        return connection.prepareStatement(query, Statement.NO_GENERATED_KEYS);
    }

    public boolean isConnected() throws SQLException {
        return connection.isValid(5000);
    }

    public boolean getAutoCommitValue() throws SQLException {
        return this.connection.getAutoCommit();
    }

    public void disableAutoCommit() throws SQLException {
        this.connection.setAutoCommit(false);
    }

    public void enableAutoCommit() throws SQLException {
        this.connection.setAutoCommit(true);
    }

    public void commit() throws SQLException {
        this.connection.commit();
    }

    public void rollback() throws SQLException {
        this.connection.rollback();
    }

    public class QueryStorage {
        List<String> storage = new ArrayList<>();

        public void add(String query) {
            storage.add(query);
        }

        public void send() throws SQLException {
            DBConnection dbConnection = DBConnection.getInstance();
            try (Statement stmt = dbConnection.getStatement()) {
                for (String query : storage) {
                    stmt.executeQuery(query);
                }
            }
        }

        public void clear() {
            storage.clear();
        }
    }
}

